#axon:
#  evenhanded:
#    processors:
#      name:
#        mode: tracking
server:
  port: 8081
spring:
  application:
    name: MANAGER SERVICE
  liquibase:
    changeLog: classpath:/db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/event_store
    driver-class-name: org.postgresql.Driver
    username: event
    password: cqrs
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect