version: '3'

services:

  db:
    image: postgres
    hostname: postgres13
    restart: always
    container_name: postgres13eventbus

    volumes:
      - /var/lib/postgresql/data

    environment:
      DB_HOST=docker: for.win.localhost
      POSTGRES_DB: event_store
      POSTGRES_USER: event
      POSTGRES_PASSWORD: cqrs
    ports:
      - "5432:5432"