version: "3"
services:
  db:
    image: "postgres:13"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=stocks
      - POSTGRES_PASSWORD=stocks
      - POSTGRES_DB=market
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-datavolume:/var/lib/postgresql/data