spring:
  liquibase:
    changeLog: classpath:/db/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/market
    user: stocks
    password: stocks
  application:
    name: stock-client
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/market
    username: stocks
    password: stocks
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
server:
  port: 8082
market:
  url: http://localhost:8081
